# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#  find the sum of the even-valued terms.


def even_fibonacci_sum(max):
    
    sum = 0

    num1 = 0
    num2 = 1

    while num1 + num2 < max:

        # temporary variables to hold previous values
        num1_old = num1
        num2_old = num2

        # slide current numbers along the series
        num1 = num2_old
        num2 = num1_old + num2_old

        # add only the even numbers to the sum
        if num2%2 == 0:
            sum+=num2


    return sum


print(even_fibonacci_sum(4000000))